<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example.github.jfrog.maven</groupId>
    <artifactId>internal-package</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.example.github.jfrog.maven</groupId>
            <artifactId>internal-utils</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>central</id>
            <name>slash-maven-virtual</name>
            <url>https://demo.jfrogchina.com/artifactory/slash-maven-whitelist</url>
        </repository>
    </repositories>

    <distributionManagement>
        <repository>
            <id>central</id>
            <name>slash-maven-local-releases</name>
            <url>https://demo.jfrogchina.com/artifactory/slash-maven-whitelist</url>
        </repository>
    </distributionManagement>
</project>