apiVersion: v1
kind: Service
metadata:
  name: slash-docker-app-maven-service
  namespace: slash-runtime-demo
spec:
  selector:
    app: docker-app-maven
  ports:
    - protocol: TCP
      port: 9090          # 外部访问端口
      targetPort: 8080  # 容器内部端口
  type: LoadBalancer
  