name: "JFrog GitHub Demo"
on:
  pull_request_target: 
    types: [opened, synchronize] # Triggers scan-pr flow for every opened/updated pull request
  push:
    branches: [demo-jfrogchina]
  workflow_dispatch: # The repository will be scanned on demand

permissions:
  # This is required for requesting the OIDC token
  id-token: write
  # This is required for actions/checkout
  contents: write
  pull-requests: write
  security-events: write
  attestations: write
  artifact-metadata: write

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branches.
        branch: ["demo-jfrogchina", "main"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run JFrog CLI Frogbot Scan
        uses: jfrog/frogbot@v2
        # [Mandatory if using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
        # Insert to oidc-provider-name the 'Provider Name' defined in the OIDC integration configured in the JPD
        # with:
        #   oidc-provider-name: slash-github
        #   oidc-audience: slash-github-audience
        env:
          JF_URL: ${{ vars.JF_CHINA_URL }}
          JF_GIT_TOKEN: ${{ secrets.SLASH_GITHUB_TOKEN }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_CHINA_ACCESS_TOKEN }}

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup JFrog CLI
  #       uses: jfrog/setup-jfrog-cli@v4
  #       env:
  #         JF_URL: ${{ vars.JF_CHINA_URL }}
  #       with:
  #         oidc-provider-name: slash-github
  #         oidc-audience: slash-github-audience

  #     - name: Run JFrog CLI
  #       run: |
  #         # Ping the server
  #         jf rt ping
  #         jf c show
      
  #     - name: Run JFrog Curation Audit
  #       working-directory: ./app-npm  # 设置工作目录
  #       run: jf curation-audit

  #     - name: Build and Publish NPM Package
  #       working-directory: ./app-npm  # 设置工作目录
  #       run: |
  #         echo "当前目录: $(pwd)"

  #         VERSION=$(node -p "require('./package.json').version")
  #         BASE_VERSION=${VERSION%.*}  # 获取主版本号 1.0
          
  #         # 使用 GitHub Actions 的 run_number 作为构建号
  #         BUILD_NUMBER=${{ github.run_number }}

  #         npm version ${BASE_VERSION}.${BUILD_NUMBER} --no-git-tag-version

  #         jf npmc --server-id-resolve=setup-jfrog-cli-server --server-id-deploy=setup-jfrog-cli-server --repo-resolve=slash-npm-virtual --repo-deploy=slash-npm-virtual
  #         jf npm install --build-name=slash-jpd-github-npm --build-number=${{github.run_number}}
  #         jf npm publish --build-name=slash-jpd-github-npm --build-number=${{github.run_number}}
  #         jf rt bce slash-jpd-github-npm ${{github.run_number}}
  #         jf rt bp slash-jpd-github-npm ${{github.run_number}}
          
  #     - name: Xray Scan Build Artifacts
  #       working-directory: ./app-npm  # 设置工作目录
  #       run: |
  #         echo "Xray Scan Build Artifacts"
  #         jf bs slash-jpd-github-npm ${{github.run_number}}

      # - name: Create Sonar evidence
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     jf evd create \
      #       --build-name $GITHUB_WORKFLOW \
      #       --build-number "${{ github.run_number }}" \
      #       --key "${{ secrets.SIGNING_KEY }}" \
      #       --key-alias ${{ vars.SIGNING_KEY_ALIAS }} \
      #       --integration sonar
      
      