# This workflow demonstrates building a Docker image, pushing it to JFrog Artifactory,
# and attaching an SLSA build provenance attestation, which is stored in JFrog Evidence.

name: Build, Push, and Attest to JFrog

on:
  push:
    branches:
      - jfrog-evidence
  workflow_dispatch:

# Use GitHub variables (vars) and secrets (secrets) for configuration
env:
  JF_URL: ${{ vars.JF_CHINA_URL }}
  JF_REPO: slash-maven-dev-local

jobs:
  build-and-attest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write      # Required for OIDC token access
      attestations: write  # Required for attestation

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_CHINA_URL }}
        with:
          oidc-provider-name: slash-github
          oidc-audience: slash-github-audience

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          jf c show

      - name: Build and Publish NPM Package
        id: build-and-push
        working-directory: ./app-maven  # 设置工作目录
        run: |
          echo "当前目录: $(pwd)"

          jf mvnc --server-id-resolve=setup-jfrog-cli-server --server-id-deploy=setup-jfrog-cli-server --repo-resolve-releases=slash-maven-virtual --repo-resolve-snapshots=slash-maven-virtual --repo-deploy-releases=slash-maven-virtual --repo-deploy-snapshots=slash-maven-virtual

          jf mvn install --build-name=slash-jpd-github-maven --build-number=${{github.run_number}}
          jf rt bce slash-jpd-github-maven ${{github.run_number}}
          jf rt bp slash-jpd-github-maven ${{github.run_number}}

      - name: Generate artifact attestation to JFrog Evidence
        uses: actions/attest-build-provenance@v3
        with:
          # The 'oci://' prefix is required by JFrog to correctly parse the artifact type
          subject-path: 'slash-maven-dev-local/com/example/github/jfrog/maven/app-maven/2.1.0/app-maven-2.1.0.war'
          
          # This links the attestation directly to the image digest from the build step
        #   subject-digest: ${{ steps.build-and-push.outputs.digest }}



